2023-05-01 13:15:16,571:INFO:bot: <botTesting Online>
2023-05-01 13:15:16,571:INFO:bot: discord.py 2.1.0
2023-05-01 13:15:23,282:ERROR:bot: Ignoring exception at on_raw_reaction_add
2023-05-01 13:15:23,284:ERROR:bot: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/bot/bot.py", line 103, in on_raw_reaction_add
    channel = guild.get_channel(team['chan_id'])
TypeError: 'NoneType' object is not subscriptable

2023-05-01 13:16:08,011:ERROR:bot: Ignoring exception at on_raw_reaction_add
2023-05-01 13:16:08,012:ERROR:bot: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/bot/bot.py", line 103, in on_raw_reaction_add
    channel = guild.get_channel(team['chan_id'])
TypeError: 'NoneType' object is not subscriptable

